version: '3.8'
services:
  astro-app:
    build: .
    ports:
      - "4321:4321"
    restart: always
    volumes:
      - /mnt/astro_data:/app/public
    environment:
      - NODE_ENV=production

volumes:
  astro_data:
    driver: local